#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o noglob

deno run -A ../somewhere/somewhere.ts

if [[ $(git status --porcelain) == '' ]] ; then
  echo "No new locations found, nothing to do"
  exit
fi

(
  cd "$(dirname "$0")"
  git add somewhere.json
  git commit -m "Update location"
  git push origin main
)
