#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o noglob


(
  cd "$(dirname "$0")"

  git pull origin main

  /Users/dylan/.deno/bin/deno run -A ../somewhere/somewhere.ts

  if [[ $(git status --porcelain) == '' ]] ; then
    echo "No new locations found, nothing to do"
    exit
  fi

  git add somewhere.json
  git commit --no-gpg-sign -m "[Automated] Update location"
  git push origin main
)
